server:
  port: 8080

spring:
  application:
    #???????
    name: ibge
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 610492
  mail:
    host: smtp.qq.com
    username: 2859068917@qq.com
    password: lgsbvrgblwxlddcc
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
mybatis-plus:
  configuration:
    #??????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0

ibge:
  path: E:\image\
